# Generated by Django 2.1.5 on 2019-10-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='server',
        ),
        migrations.AddField(
            model_name='server',
            name='connection',
            field=models.ForeignKey(blank=True, null=True, on_delete=True, related_name='server', to='cmdb.Connection', verbose_name='连接信息'),
        ),
    ]
