# Generated by Django 2.1.5 on 2019-11-01 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20191031_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invertory_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=128, verbose_name='组名')),
                ('server', models.ManyToManyField(blank=True, null=True, related_name='invertory', to='cmdb.Server', verbose_name='所属服务器')),
            ],
            options={
                'verbose_name': '资产组',
                'verbose_name_plural': '资产组',
                'db_table': 'invertory',
            },
        ),
    ]
