# Generated by Django 2.1.5 on 2019-11-01 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_invertory_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invertory_group',
            name='server',
            field=models.ManyToManyField(related_name='invertory', to='cmdb.Server', verbose_name='所属服务器'),
        ),
    ]
