# Generated by Django 2.1.5 on 2019-11-06 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20191101_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='variable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=128, verbose_name='变量名')),
                ('value', models.CharField(max_length=128, verbose_name='变量值')),
                ('group', models.ManyToManyField(related_name='inventory_group', to='cmdb.Invertory_group', verbose_name='所属组')),
                ('host', models.ManyToManyField(related_name='variable', to='cmdb.Server', verbose_name='所属主机')),
            ],
            options={
                'verbose_name': '变量',
                'verbose_name_plural': '变量',
                'db_table': 'variable',
            },
        ),
    ]
