# Generated by Django 2.1.5 on 2019-11-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0006_auto_20191106_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable',
            name='group',
            field=models.ManyToManyField(related_name='variable_group', to='cmdb.Invertory_group', verbose_name='所属组'),
        ),
        migrations.AlterField(
            model_name='variable',
            name='host',
            field=models.ManyToManyField(blank=True, null=True, related_name='variable_server', to='cmdb.Server', verbose_name='所属主机'),
        ),
    ]
