# Generated by Django 2.1.5 on 2019-11-06 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0008_auto_20191106_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable2Group2Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_group', to='cmdb.Invertory_group', verbose_name='所属组')),
                ('variable_hosts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_hosts', to='cmdb.Server', verbose_name='所属主机')),
                ('variable_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_name', to='cmdb.Variable', verbose_name='变量')),
            ],
            options={
                'verbose_name': '变量关系表',
                'verbose_name_plural': '变量关系表',
                'db_table': 'variable_host_group',
            },
        ),
    ]
