# Generated by Django 2.1.5 on 2019-11-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0009_variable2group2server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable2group2server',
            name='variable_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_group', to='cmdb.Invertory_group', verbose_name='所属组'),
        ),
        migrations.AlterField(
            model_name='variable2group2server',
            name='variable_hosts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_hosts', to='cmdb.Server', verbose_name='所属主机'),
        ),
        migrations.AlterField(
            model_name='variable2group2server',
            name='variable_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_name', to='cmdb.Variable', verbose_name='变量'),
        ),
    ]
