# Generated by Django 2.1.5 on 2019-11-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0010_auto_20191106_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variable2group2server',
            name='variable_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variable_name', to='cmdb.Variable', verbose_name='变量'),
        ),
    ]
